version: '3'

services:
  simulation:
    image: mysteriouscrawler/test
    ports:
      - '3000:3000'
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start:prod
    ports:
      - '8080:8080'
    depends_on:
      - simulation
    environment:
      - RTC_SIMULATION_API_PORT=3000
      - RTC_SIMULATION_API_URL=http://simulation
      - RTC_SIMULATION_ROOT_PATH=/api
      - RTC_SIMULATION_DURATION_MIN=5
      - CRAWLER_APPLICATION_PORT=8080
      - POLLING_INTERVAL=1000
    volumes:
      - /app/workspace/services
    develop:
      watch:
        - action: rebuild
          path: ./
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
